name: Build Kivy APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools python3-wheel git zip openjdk-11-jdk unzip wget
          pip install --upgrade pip
          pip install buildozer cython

      - name: Install Android SDK & NDK
        run: |
          # Create .buildozer sdk folder
          mkdir -p $HOME/.buildozer/android/platform/android-sdk/cmdline-tools
          
          # Download older command-line tools compatible with Buildozer
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip -d $HOME/.buildozer/android/platform/android-sdk/cmdline-tools
          
          # Create legacy tools/bin for Buildozer
          mkdir -p $HOME/.buildozer/android/platform/android-sdk/tools/bin
          cp -r $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/cmdline-tools/bin/* $HOME/.buildozer/android/platform/android-sdk/tools/bin/
          
          # Set environment variables
          export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
          export PATH=$ANDROID_HOME/tools/bin:$PATH
          export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
          
          # Accept licenses and install platforms/build-tools/NDK
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.2.9519653"

      - name: Build APK
        run: |
          buildozer init || true
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: bin/*.apk
