name: Build Kivy APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools python3-wheel git zip openjdk-17-jdk unzip wget
          pip install --upgrade pip
          pip install buildozer cython

            - name: Install Android SDK & NDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/cmdline-tools/bin:$PATH
          yes | $HOME/android-sdk/cmdline-tools/cmdline-tools/bin/sdkmanager --licenses
          $HOME/android-sdk/cmdline-tools/cmdline-tools/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.2.9519653"
          
          # Copy build-tools into .buildozer where Buildozer looks
          mkdir -p $HOME/.buildozer/android/platform/android-sdk/
          cp -r $ANDROID_HOME/build-tools $HOME/.buildozer/android/platform/android-sdk/
          cp -r $ANDROID_HOME/platforms $HOME/.buildozer/android/platform/android-sdk/
          cp -r $ANDROID_HOME/platform-tools $HOME/.buildozer/android/platform/android-sdk/


      - name: Build APK
        run: |
          buildozer init || true
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: bin/*.apk
